# Generated by Django 2.1.3 on 2020-08-22 15:04

import commons.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eurowiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(blank=True, null=True, verbose_name='query result')),
                ('executed', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='execution time')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executor', to=settings.AUTH_USER_MODEL, verbose_name='executor')),
            ],
            options={
                'verbose_name': 'SPARQL query execution',
                'verbose_name_plural': 'SPARQL query executions',
            },
        ),
        migrations.CreateModel(
            name='SparqlQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('text', models.TextField(blank=True, null=True, verbose_name='query text')),
                ('state', models.IntegerField(choices=[(-3, 'Portlet'), (-1, 'Grey'), (1, 'Draft'), (2, 'Submitted'), (3, 'Published'), (4, 'Un-published')], default=1, null=True, verbose_name='publication state')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='last modified')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='query_editor', to=settings.AUTH_USER_MODEL, verbose_name='last editor')),
            ],
            options={
                'verbose_name': 'SPARQL query definition',
                'verbose_name_plural': 'SPARQL query definitions',
            },
            bases=(models.Model, commons.models.Publishable),
        ),
        migrations.AddField(
            model_name='queryrun',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query', to='eurowiki.SparqlQuery', verbose_name='query'),
        ),
    ]
